### ISSUE TITLE
demo-not-working

### ISSUE THREAD

**Issue by AnandSrini** [tangrams/shaders-demo#3]
Please check the demo page http://tangrams.github.io/shaders-demo/

It's always blank, running on chrome 77.0.3865.120 (latest as of now)

I have also tried running the master branch in my local (using the python command)

Error details:
GET https://www.mapzen.com/tangram/0.11/tangram.min.js net::ERR_ABORTED 404
main.js:27 Uncaught ReferenceError: Tangram is not defined
    at main.js:27
    at main.js:162
(anonymous) @ main.js:27
(anonymous) @ main.js:162
(index):51 GET https://www.mapzen.com/common/ui/mapzen-ui.min.js net::ERR_ABORTED 404
(index):53 Uncaught ReferenceError: MPZN is not defined
    at (index):53

**Comment by bcamper** [comment]
Thank you, made some updates to point to new versions of libraries and styling and good to go again!
